name: Maven Test

on:
  push:
    branches:
      - main   # This will trigger on pushes to the main branch
      - feature/* # This will trigger on pushes to branches with 'feature/' prefix 
  pull_request:
    branches:
      - main   # This will trigger on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Run Tests
        run: mvn clean test
