name: Run Maven Tests on Pull Request

on:
  pull_request:
    branches:
      - main  # This ensures that the workflow only triggers when a PR is created/updated for the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Set the Java version for your project

      - name: Install Maven dependencies
        run: mvn install -DskipTests

      - name: Run tests
        run: mvn test  # This runs the tests using Maven
