name: Maven Test Workflow

on:
  push:
    branches:
      - 'main'
      - 'feature/*'  # Runs on push to 'main' and 'feature' branches
  pull_request:
    branches:
      - 'main'  # Runs tests on pull requests targeting the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Use the appropriate Java version
      - name: Run Tests
        run: mvn test  # Run Maven tests
